server:
  port: 8080

# spring:
#   datasource:
#     url: jdbc:postgresql://localhost:5432/hms_db
#     username: postgres
#     password: postgres
#   jpa:
#     hibernate:
#       ddl-auto: update
#     show-sql: true
#     properties:
#       hibernate:
#         format_sql: true
#     open-in-view: false
spring:
  datasource:
    url: jdbc:h2:mem:hospitaldb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console
  mail:
    host: smtp.gmail.com
    port: 587
    username: prakashkhuntia93@gmail.com
    password: nixb drwk koet xdjw
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  jwt:
    secret: "ReplaceThisWithA256BitSecretKeyForJwtSigningInProdEnv!"
    expiration-ms: 86400000 # 24 hours
  frontend-url: http://localhost:5173
  reset-url: http://localhost:8080/api/auth/browser-reset

ai-service:
  base-url: http://localhost:8000
